"""Tests for the generated Prometheus rules.

These check the contract the CLI and the CI job rely on: file names, metric
names, window wiring, severities, the runbook link, and that the YAML is a valid
rule file. The deeper check -- ``promtool check rules`` -- runs in CI against the
latest Prometheus release and in ``make promtool-check`` locally.
"""

from __future__ import annotations

from pathlib import Path

import pytest
import yaml

from sloctl.config import load_config_dir
from sloctl.models import ALERT_BURN_WINDOWS, ALERT_FOR, RATIO_WINDOWS
from sloctl.rules import RUNBOOK_URL, ratio_windows, rule_documents, write_rules

REPO_ROOT = Path(__file__).resolve().parents[1]
CONFIG_DIR = REPO_ROOT / "examples" / "slo"
EXPECTED_SERVICES = ("checkout", "payments", "search")


@pytest.fixture(scope="module")
def slos():
    return load_config_dir(CONFIG_DIR)


@pytest.fixture(scope="module")
def generated(tmp_path_factory, slos):
    out_dir = tmp_path_factory.mktemp("rules")
    written = write_rules(slos, out_dir)
    return out_dir, written


def load(path: Path):
    return yaml.safe_load(path.read_text(encoding="utf-8"))


def rules_of(document):
    return [rule for group in document["groups"] for rule in group["rules"]]


def test_two_files_per_service(generated):
    out_dir, written = generated
    assert [path.name for path in written] == sorted(
        "%s_%s.rules.yml" % (service, kind) for service in EXPECTED_SERVICES for kind in ("alerts", "recording")
    )
    for path in written:
        assert path.exists() and path.stat().st_size > 0
        assert path.read_text(encoding="utf-8").startswith("# Generated by `sloctl rules generate`")


def test_recording_metrics_use_the_documented_names(generated):
    out_dir, _ = generated
    recorded = {rule["record"] for rule in rules_of(load(out_dir / "checkout_recording.rules.yml"))}
    assert "checkout:sli_availability:ratio_rate1h" in recorded
    assert "checkout:sli_availability:ratio_rate5m" in recorded
    assert "checkout:sli_availability:ratio_rate30d" in recorded  # the SLO window itself
    assert "checkout:slo:error_budget_remaining" in recorded
    assert "checkout:slo:error_budget_consumed" in recorded
    for window in RATIO_WINDOWS:
        assert "checkout:slo:burn_rate%s" % window in recorded


def test_recording_rule_labels_are_stable(generated):
    out_dir, _ = generated
    for rule in rules_of(load(out_dir / "search_recording.rules.yml")):
        assert rule["labels"]["service"] == "search"
        assert rule["labels"]["sli"] == "availability"
        if rule["record"] == "search:slo:error_budget_remaining":
            assert rule["labels"]["slo_target"] == "0.995"
            assert rule["labels"]["window"] == "30d"
        else:
            assert "window" in rule["labels"]


def test_range_selector_is_rewritten_per_window(generated):
    out_dir, _ = generated
    by_name = {rule["record"]: rule["expr"] for rule in rules_of(load(out_dir / "payments_recording.rules.yml"))}
    assert "[1h]" in by_name["payments:sli_availability:ratio_rate1h"]
    assert "[5m]" not in by_name["payments:sli_availability:ratio_rate1h"]
    assert "[6h]" in by_name["payments:slo:burn_rate6h"]
    assert 'job="payments-api"' in by_name["payments:slo:burn_rate6h"]


def test_burn_rate_expression_divides_by_the_allowed_error_ratio(generated):
    out_dir, _ = generated
    by_name = {rule["record"]: rule["expr"] for rule in rules_of(load(out_dir / "search_recording.rules.yml"))}
    expression = by_name["search:slo:burn_rate3d"]
    assert "(1 - 0.005)" in expression
    assert "[3d]" in expression


def test_error_budget_remaining_is_derived_from_the_window_ratio(generated):
    out_dir, _ = generated
    by_name = {rule["record"]: rule["expr"] for rule in rules_of(load(out_dir / "checkout_recording.rules.yml"))}
    expression = by_name["checkout:slo:error_budget_remaining"]
    assert "checkout:sli_availability:ratio_rate30d" in expression
    assert "(1 - 0.001)" in expression


def test_alerts_follow_the_multi_window_multi_burn_rate_pairs(generated):
    out_dir, _ = generated
    alerts = {rule["alert"]: rule for rule in rules_of(load(out_dir / "payments_alerts.rules.yml"))}
    assert sorted(alerts) == [
        "PaymentsSLOErrorBudgetBurn1h",
        "PaymentsSLOErrorBudgetBurn3d",
        "PaymentsSLOErrorBudgetBurn6h",
    ]
    for window in ALERT_BURN_WINDOWS:
        rule = alerts["PaymentsSLOErrorBudgetBurn%s" % window.label]
        assert rule["labels"]["severity"] == window.severity
        assert rule["labels"]["window"] == window.label
        assert rule["labels"]["short_window"] == window.short_label
        assert rule["for"] == ALERT_FOR[window.label]
        assert "> %s" % window.fast_threshold in rule["expr"]
        assert "payments:slo:burn_rate%s" % window.label in rule["expr"]
        assert "payments:slo:burn_rate%s" % window.short_label in rule["expr"]


def test_page_alert_is_the_14_4x_hour_pair():
    page = [window for window in ALERT_BURN_WINDOWS if window.severity == "page"]
    assert len(page) == 1
    assert page[0].label == "1h"
    assert page[0].short_label == "5m"
    assert str(page[0].fast_threshold) == "14.4"


def test_alerts_carry_runbook_and_budget_impact(generated):
    out_dir, _ = generated
    for rule in rules_of(load(out_dir / "checkout_alerts.rules.yml")):
        annotations = rule["annotations"]
        assert annotations["runbook_url"] == RUNBOOK_URL
        assert "checkout" in annotations["summary"]
        assert "error budget" in annotations["description"]
        assert "30d" in annotations["description"]


def test_alerts_inherit_the_service_labels_from_the_slo(generated):
    out_dir, _ = generated
    for rule in rules_of(load(out_dir / "search_alerts.rules.yml")):
        assert rule["labels"]["team"] == "search"
        assert rule["labels"]["tier"] == "2"
        assert rule["labels"]["slo_target"] == "0.995"


def test_generated_yaml_is_a_well_formed_rule_file(generated):
    out_dir, written = generated
    for path in written:
        document = load(path)
        assert list(document) == ["groups"]
        assert len(document["groups"]) == 1
        for group in document["groups"]:
            assert group["name"].endswith(("_slo_recording", "_slo_alerts"))
            assert group["rules"]
            for rule in group["rules"]:
                assert ("record" in rule) != ("alert" in rule)
                assert isinstance(rule["expr"], str) and rule["expr"].strip()
                assert rule["expr"].count("(") == rule["expr"].count(")")
                for label in rule.get("labels", {}).values():
                    assert isinstance(label, str)


def test_metric_and_alert_names_are_unique(generated):
    out_dir, written = generated
    recorded, alerts = [], []
    for path in written:
        for rule in rules_of(load(path)):
            (recorded if "record" in rule else alerts).append(rule.get("record") or rule.get("alert"))
    assert len(recorded) == len(set(recorded))
    assert len(alerts) == len(set(alerts))


def test_every_recorded_metric_starts_with_the_service(slos):
    for slo in slos:
        for _name, document in rule_documents(slo).items():
            for rule in rules_of(document):
                if "record" in rule:
                    assert rule["record"].startswith("%s:" % slo.service)


def test_recording_windows_include_the_slo_window_sorted(slos):
    checkout = next(slo for slo in slos if slo.service == "checkout")
    assert ratio_windows(checkout) == ("5m", "30m", "1h", "6h", "1d", "3d", "30d")
