"""Render evaluation results as a Markdown report.

The report is meant to be readable in a pull request, an issue or a
``reports/slo-report.md`` artifact: tables first, then the exact definitions that
produced the numbers, then the caveats.
"""

from __future__ import annotations

from datetime import datetime, timezone
from decimal import Decimal
from typing import Iterable, Optional, Sequence

from .engine import format_duration
from .models import SLO, BurnMeasurement, Evaluation

STATUS_ORDER = {"violated": 0, "compliant": 1}
VERDICT_ORDER = {"fast burn": 0, "slow burn": 1, "ok": 2, "no data": 3}


def format_percent(value: Optional[Decimal], digits: int = 2) -> str:
    """Decimal ratio -> ``99.9%`` style string (trailing zeros trimmed)."""
    if value is None:
        return "n/a"
    if value.is_infinite():
        return ">100%"
    text = ("%%.%df" % digits) % (value * 100)
    if "." in text:
        text = text.rstrip("0").rstrip(".")
    return "%s%%" % text


def format_ratio(value: Optional[Decimal], digits: int = 4) -> str:
    if value is None:
        return "n/a"
    return ("%%.%df" % digits) % value


def format_count(value: Decimal) -> str:
    integral = value.to_integral_value()
    if value == integral:
        return "{:,}".format(int(integral))
    return "{:,.2f}".format(float(value))


def format_burn(value: Optional[Decimal]) -> str:
    if value is None:
        return "n/a"
    if value.is_infinite():
        return "inf"
    if value >= 1000:
        return "{:,.0f}x".format(float(value))
    if value >= 100:
        return "{:.0f}x".format(float(value))
    return "{:.2f}x".format(float(value))


def format_eta(measurement: BurnMeasurement) -> str:
    if measurement.total == 0:
        return "no data"
    if measurement.eta_seconds is None:
        return "stable"
    if measurement.eta_seconds == 0:
        return "exhausted"
    return format_duration(measurement.eta_seconds)


def format_objective(objective: Decimal) -> str:
    text = format((objective * 100).normalize(), "f")
    if "." in text:
        text = text.rstrip("0").rstrip(".")
    return "%s%%" % text


def budget_table(evaluations: Sequence[Evaluation]) -> str:
    rows = [
        "| Service | SLI | Objective | Window | Budget | Consumed | Remaining | Status |",
        "| --- | --- | --- | --- | --- | --- | --- | --- |",
    ]
    for evaluation in sorted(evaluations, key=lambda item: (STATUS_ORDER[item.status], item.slo.service)):
        budget = evaluation.budget
        rows.append(
            "| %s | %s | %s | %s | %s | %s (%s) | %s | %s |"
            % (
                evaluation.slo.service,
                evaluation.slo.sli.name,
                format_objective(evaluation.slo.objective),
                evaluation.slo.window,
                format_duration(budget.total_seconds),
                format_duration(budget.consumed_seconds),
                format_percent(budget.consumed_ratio, 1),
                format_percent(budget.remaining_ratio, 1),
                evaluation.status,
            )
        )
    return "\n".join(rows)


def burn_table(evaluations: Sequence[Evaluation]) -> str:
    rows = [
        "| Service | Window | Good / Total | Error ratio | Burn rate | Verdict | ETA |",
        "| --- | --- | --- | --- | --- | --- | --- |",
    ]
    for evaluation in sorted(evaluations, key=lambda item: (STATUS_ORDER[item.status], item.slo.service)):
        for measurement in sorted(evaluation.burns, key=lambda item: VERDICT_ORDER[item.verdict]):
            rows.append(
                "| %s | %s | %s / %s | %s | %s | %s | %s |"
                % (
                    evaluation.slo.service,
                    measurement.window.label,
                    format_count(measurement.good),
                    format_count(measurement.total),
                    format_percent(measurement.error_ratio, 3),
                    format_burn(measurement.burn_rate),
                    measurement.verdict,
                    format_eta(measurement),
                )
            )
    return "\n".join(rows)


def render_report(
    evaluations: Sequence[Evaluation],
    generated_at: Optional[datetime] = None,
    sources: Optional[Iterable[SLO]] = None,
) -> str:
    """Full Markdown report for a set of evaluated SLOs."""
    stamped = generated_at or datetime.now(timezone.utc)
    total = len(evaluations)
    violated = [evaluation for evaluation in evaluations if evaluation.status == "violated"]
    alerting = [evaluation for evaluation in evaluations if evaluation.alerting_windows]

    lines = [
        "# SLO and error budget report",
        "",
        "Generated by `sloctl report` from declarative SLOs and synthetic sample series.",
        "Every number below is computed by `sloctl.engine`; the formulas live in",
        "[docs/slo-theory.md](../docs/slo-theory.md).",
        "",
        "Generated at: %s" % stamped.astimezone(timezone.utc).strftime("%Y-%m-%dT%H:%M:%SZ"),
        "",
        "## Summary",
        "",
        "- %d service(s) evaluated: %s" % (total, ", ".join(sorted(e.slo.service for e in evaluations))),
        "- %d service(s) over budget: %s"
        % (len(violated), ", ".join(sorted(e.slo.service for e in violated)) or "none"),
        "- %d service(s) with a burn rate at or above the page threshold: %s"
        % (len(alerting), ", ".join(sorted(e.slo.service for e in alerting)) or "none"),
        "",
        "## Error budgets",
        "",
        "Consumed time is the bad time the samples account for; the budget is the bad time the",
        "objective allows over the full window. `Remaining` is what is left of the budget, as a",
        "percentage of it.",
        "",
        budget_table(evaluations),
        "",
        "## Burn rates",
        "",
        'Burn rate 1 means "at this rate the whole budget is gone in exactly one window".',
        "`fast burn` is at or above the page threshold of the window, `slow burn` is at or above",
        "1 but below that threshold, `ok` is below 1.",
        "",
        burn_table(evaluations),
        "",
        "## Definitions applied",
        "",
        "- `budget_seconds = window_seconds * (1 - objective)`",
        "- `consumed_seconds = (1 - good/total) * coverage_seconds`",
        "- `burn_rate = (1 - good/total) / (1 - objective)` over the lookback window",
        "- `eta = remaining_ratio * window_seconds / burn_rate` (`stable` when the burn rate is 0)",
        "- `compliant` when `consumed_seconds <= budget_seconds`",
        "",
        "## Coverage notes",
        "",
    ]
    for evaluation in sorted(evaluations, key=lambda item: item.slo.service):
        budget = evaluation.budget
        note = "full window coverage" if not budget.partial_coverage else "PARTIAL coverage"
        lines.append(
            "- **%s**: samples cover %s of the %s window (%s). Consumed %s of %s; worst burn rate %s (%s)."
            % (
                evaluation.slo.service,
                format_duration(budget.coverage_seconds),
                evaluation.slo.window,
                note,
                format_duration(budget.consumed_seconds),
                format_duration(budget.total_seconds),
                format_burn(evaluation.worst_burn.burn_rate if evaluation.worst_burn else None),
                evaluation.worst_burn.window.label if evaluation.worst_burn else "n/a",
            )
        )

    lines += [
        "",
        "## How to reproduce",
        "",
        "```bash",
        "make setup",
        "make budget",
        "make burn",
        "make report",
        "```",
        "",
    ]
    return "\n".join(lines)
