"""Turn SLO definitions into Prometheus recording and alerting rules.

Two files are written per service:

* ``<service>_recording.rules.yml`` -- SLI ratios, burn rates and the remaining
  error budget, at every window the alerts or the CLI need.
* ``<service>_alerts.rules.yml`` -- multi-window multi-burn-rate alerts in the
  spirit of the SRE Workbook: a long window decides whether the budget really
  burns, a short window decides whether it is still burning now. The pair is
  what keeps a five-minute blip from paging anyone.

Both are plain Prometheus rule files; the CI job (and ``make rules-check``)
feeds them to ``promtool check rules``.
"""

from __future__ import annotations

from pathlib import Path
from typing import Dict, List, Mapping, Sequence, Tuple

import yaml

from . import promql
from .engine import parse_duration
from .errors import ConfigError
from .models import ALERT_BURN_WINDOWS, ALERT_FOR, RATIO_WINDOWS, SLO, BurnWindow

FILE_HEADER = (
    "# Generated by `sloctl rules generate`. Edit examples/slo/*.yaml, not this file.\n"
    "# Validate with: promtool check rules <this file>\n"
)
RUNBOOK_URL = "https://github.com/dayxus/sre-runbooks-postmortem"


class _Emitter(yaml.SafeDumper):
    """Dumper that keeps multi-line PromQL readable instead of escaping it."""


def _represent_string(dumper: yaml.SafeDumper, value: str) -> yaml.ScalarNode:
    if "\n" in value:
        return dumper.represent_scalar("tag:yaml.org,2002:str", value, style="|")
    return dumper.represent_scalar("tag:yaml.org,2002:str", value)


_Emitter.add_representer(str, _represent_string)


def ratio_windows(slo: SLO) -> Tuple[str, ...]:
    """Recording windows for one SLO, sorted by duration."""
    windows = list(RATIO_WINDOWS)
    if slo.window not in windows:
        windows.append(slo.window)
    return tuple(sorted(windows, key=parse_duration))


def burn_windows(slo: SLO) -> Tuple[str, ...]:
    """Every window a burn rate is recorded at (superset of the alert windows)."""
    return ratio_windows(slo)


def recording_group(slo: SLO) -> Dict[str, object]:
    """One recording-rule group for a service."""
    service = promql.sanitize_identifier(slo.service)
    rules: List[Mapping[str, object]] = []

    for window in ratio_windows(slo):
        rules.append(
            {
                "record": promql.ratio_name(slo.service, slo.sli.name, window),
                "expr": promql.ratio_expr(slo, window),
                "labels": {
                    "service": slo.service,
                    "sli": slo.sli.name,
                    "window": window,
                },
            }
        )

    rules.append(
        {
            "record": promql.budget_remaining_name(slo.service),
            "expr": promql.error_budget_remaining_expr(slo),
            "labels": {
                "service": slo.service,
                "sli": slo.sli.name,
                "slo_target": str(slo.objective),
                "window": slo.window,
            },
        }
    )
    rules.append(
        {
            "record": promql.budget_consumed_name(slo.service),
            "expr": promql.error_budget_consumed_expr(slo),
            "labels": {
                "service": slo.service,
                "sli": slo.sli.name,
                "slo_target": str(slo.objective),
                "window": slo.window,
            },
        }
    )

    for window in burn_windows(slo):
        rules.append(
            {
                "record": promql.burn_rate_name(slo.service, window),
                "expr": promql.burn_rate_expr(slo, window),
                "labels": {
                    "service": slo.service,
                    "sli": slo.sli.name,
                    "slo_target": str(slo.objective),
                    "window": window,
                },
            }
        )

    return {
        "name": "%s_slo_recording" % service,
        "interval": "30s",
        "rules": rules,
    }


def _alert_name(service: str, window: BurnWindow) -> str:
    return "%sSLOErrorBudgetBurn%s" % (promql.camel_case(service), window.label)


def _alert_expr(slo: SLO, window: BurnWindow) -> str:
    long_metric = promql.burn_rate_name(slo.service, window.label)
    short_metric = promql.burn_rate_name(slo.service, window.short_label)
    return "%s > %s\nand\n%s > %s" % (long_metric, window.fast_threshold, short_metric, window.short_threshold)


def _alert_labels(slo: SLO, window: BurnWindow) -> Dict[str, str]:
    labels = {
        "severity": window.severity,
        "service": slo.service,
        "sli": slo.sli.name,
        "slo_target": str(slo.objective),
        "window": window.label,
        "short_window": window.short_label,
    }
    for key, value in sorted(slo.labels.items()):
        labels.setdefault(key, value)
    return labels


def _alert_annotations(slo: SLO, window: BurnWindow) -> Dict[str, str]:
    window_human = "%s/%s" % (window.label, window.short_label)
    summary = "%s is burning its %s error budget %.1fx too fast (%s)" % (
        slo.service,
        slo.window,
        float(window.fast_threshold),
        window_human,
    )
    description = (
        "The %s %s objective of %s is being missed at the current rate: the %s window "
        "burns the error budget more than %.1fx faster than allowed and the %s window confirms "
        "the burn is still happening (current burn rate {{ $value }}x). "
        "Budget spent at this pace is irreversible inside the %s window, so the remaining "
        "error budget must be defended by freezing risky changes or by failing over. "
        "Follow the runbook before acknowledging."
        % (
            slo.service,
            slo.sli.name,
            _percent(slo.objective),
            window.label,
            float(window.fast_threshold),
            window.short_label,
            slo.window,
        )
    )
    return {
        "summary": summary,
        "description": description,
        "runbook_url": RUNBOOK_URL,
    }


def _percent(objective: object) -> str:
    value = float(objective) * 100
    text = ("%.4f" % value).rstrip("0").rstrip(".")
    return "%s%%" % text


def alert_group(slo: SLO) -> Dict[str, object]:
    """One alerting-rule group for a service, one rule per burn-rate pair."""
    rules: List[Mapping[str, object]] = []
    for window in ALERT_BURN_WINDOWS:
        if not window.has_alert_pair:
            raise ConfigError("burn window %s has no companion short window" % window.label)
        rules.append(
            {
                "alert": _alert_name(slo.service, window),
                "expr": _alert_expr(slo, window),
                "for": ALERT_FOR[window.label],
                "labels": _alert_labels(slo, window),
                "annotations": _alert_annotations(slo, window),
            }
        )
    return {
        "name": "%s_slo_alerts" % promql.sanitize_identifier(slo.service),
        "rules": rules,
    }


def rule_documents(slo: SLO) -> Dict[str, Mapping[str, object]]:
    """The two rule files a service produces, keyed by file name."""
    service = promql.sanitize_identifier(slo.service)
    return {
        "%s_recording.rules.yml" % service: {"groups": [recording_group(slo)]},
        "%s_alerts.rules.yml" % service: {"groups": [alert_group(slo)]},
    }


def render(document: Mapping[str, object], slo: SLO) -> str:
    body = yaml.dump(
        document,
        Dumper=_Emitter,
        default_flow_style=False,
        sort_keys=False,
        width=120,
        allow_unicode=True,
    )
    return "%s# Source: %s\n%s" % (FILE_HEADER, slo.source or slo.service, body)


def write_rules(slos: Sequence[SLO], out_dir: Path) -> List[Path]:
    """Write every rule file for ``slos`` into ``out_dir`` and return the paths."""
    out_dir = Path(out_dir)
    out_dir.mkdir(parents=True, exist_ok=True)
    written: List[Path] = []
    for slo in slos:
        for file_name, document in rule_documents(slo).items():
            path = out_dir / file_name
            path.write_text(render(document, slo), encoding="utf-8")
            written.append(path)
    return sorted(written)


def load_rules_file(path: Path) -> Mapping[str, object]:
    """Read a generated rule file back (used by the tests)."""
    document = yaml.safe_load(Path(path).read_text(encoding="utf-8"))
    if not isinstance(document, dict) or "groups" not in document:
        raise ConfigError("%s is not a Prometheus rule file" % path)
    return document
